### PR TITLE
Optimized code in injector and added a possibility for method chaining

### PR DESCRIPTION
**Pull request by ova2**
We use a fork of your great library with some patched code which I now committed in this PR. All tests are green.

- Optimized code in injector (more concise and faster for some methods).
- Added a possibility to chain method calls using cascade operator.

Thanks for accepting this PR in advance. I would be happy if you could release a new version of this lib.

### CODE REVIEW

**Comment by jonsamwell** [comment]
Thanks for this, the code looks good.  I'll have a bit of time to merge this in tomorrow and do a new release.

Is this test still passing?

https://github.com/jonsamwell/flutter_simple_dependency_injection/blob/master/test/flutter_simple_dependency_injection_test.dart#L199

**Comment by ova2** [comment]
Yes, test is still passing of course. Many thanks too!

Jon Samwell <notifications@github.com> schrieb am Fr., 23. Okt. 2020, 10:40:

**Comment by ova2** [comment]
@jonsamwell I've updated this pull request. The Injector class has a factory constructor now. An Injector instance can be instantiated more shorter. "Injector.getInjector()" is marked as deprecated as discussed here https://github.com/jonsamwell/flutter_simple_dependency_injection/issues/16

I've updated CHANGELOG too.

Looking forward for a new release!

**Comment by jonsamwell** [comment]
@ova2 many thanks for this PR.  Released as version 1.0.4

**Comment by ova2** [comment]
@jonsamwell Many thanks for release too.

**Pull request merged**
