### PR TITLE
NullSafety & Overriding option.

### PR DESCRIPTION
**Pull request by rcorbellini**
- Create a nammed parameter called `overriding` by default your value are `false` (for compatibility with existing behavior);
- Create test for existing behavior (not allowed override), and the new one (allowed override).

### CODE REVIEW

**Comment by rcorbellini** [comment]
Adding suport a Null-safety.
Resolves https://github.com/jonsamwell/flutter_simple_dependency_injection/issues/18

**Comment by navaronbracke** [comment]
Why would we need the `overriding` option in the first place? Assuming that from this version onwards you have to support NNBD anyways?

**Comment by rcorbellini** [comment]
when working with multiple flavors and want to have a standard behavior and a behavior overridden by a flavor is very useful.

**Comment by rcorbellini** [comment]
> support

https://github.com/jonsamwell/flutter_simple_dependency_injection/pull/14#issuecomment-801059470

**Comment by rcorbellini** [comment]
> Why would we need the `overriding` option in the first place? Assuming that from this version onwards you have to support NNBD anyways?

https://github.com/jonsamwell/flutter_simple_dependency_injection/pull/14#issuecomment-801059470

**Comment by rcorbellini** [comment]
> Why would we need the `overriding` option in the first place? Assuming that from this version onwards you have to support NNBD anyways?

when working with multiple flavors and want to have a standard behavior and a behavior overridden by a flavor is very useful.

**Comment by navaronbracke** [comment]
In that case I would work with one injector that gets different mappings? E.g. a set of types for `Build Flavor A` and one for `Build Flavor B` (or production / test or whatever)

**Comment by rafaelcorbellini-egsys** [comment]
when working with a core, the core has no knowledge of the children, in this case it will only resolve through the injected interface, and each child (flavor) injects its desired behavior (overriding existent) or leaves the default behavior.

You can check example GetIt has a property  `bool allowReassignment = false;`, you can set true and make override.

**Comment by rafaelcorbellini-egsys** [comment]
you can always remove and re-set the factory on injector, but this boilerplate is not cool =\

**Comment by satishsoni777** [comment]
Hi, @jonsamwell 

First of all, Thanks for creating such a nice package of DI, 

I am using this package in My project, which I have migrated. My project to null safety but, I am not able to migrate completely, because `flutter_simple_dependency_injection` is in null safety, can you please merge this Mr, to your package so we can migrate our project, completely.


Thanks.
Satish,

**Comment by jonsamwell** [comment]
@rcorbellini I've migrated to null-safety in the master branch and tweak your idea a little in regard to allowing re-mapping.  I've added the concept to allow re-mapping at the type factory level as your version allowed remapping even if the initial mapping specified it to false and I think this should be a conscious design time decision.

**Pull request closed without merging**
